# Descarga Maven automaticamente la primera vez que corres ./mvnw.
# distributionType=only-script evita tener que versionar un .jar binario en el repo.
wrapperVersion=3.3.4
distributionType=only-script
distributionUrl=https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.9.16/apache-maven-3.9.16-bin.zip
